"""Tasmanian localities, for the suburb field's autocomplete.

Extracted from the 239 distinct localities that appeared in the V1
QGIS dataset, with the "locality not found" sentinel and two misspellings
removed. It is a convenience list, not a validation whitelist — the suburb
field accepts free text, because this covers the places pets went missing in
one particular year and Tasmania has many more.
"""

LOCALITIES = [
    "Acacia Hills",
    "Acton",
    "Alcomie",
    "Ambleside",
    "Apslawn",
    "Austins Ferry",
    "Bagdad",
    "Barrington",
    "Battery Point",
    "Beaconsfield",
    "Beauty Point",
    "Bellerive",
    "Berriedale",
    "Bicheno",
    "Binalong Bay",
    "Blackmans Bay",
    "Blackstone Heights",
    "Blessington",
    "Boat Harbour",
    "Bonnet Hill",
    "Boobyalla",
    "Breadalbane",
    "Bridgenorth",
    "Bridgewater",
    "Bridport",
    "Brighton",
    "Brooklyn",
    "Brooks Bay",
    "Bruny Island",
    "Burnie",
    "Cambridge",
    "Campania",
    "Campbell Town",
    "Castle Forbes Bay",
    "Chigwell",
    "Chudleigh",
    "Claremont",
    "Clarendon Vale",
    "Collinsvale",
    "Connellys Marsh",
    "Cygnet",
    "Deloraine",
    "Devon Hills",
    "Devonport",
    "Dodges Ferry",
    "Dromedary",
    "Eaglehawk Neck",
    "East Devonport",
    "East Ulverstone",
    "Elliott",
    "Erriba",
    "Evandale",
    "Exeter",
    "Fingal",
    "Forcett",
    "Forth",
    "Frankford",
    "Franklin",
    "Gagebrook",
    "Garden Island Creek",
    "Geeveston",
    "George Town",
    "Glengarry",
    "Glenorchy",
    "Goodwood",
    "Granton",
    "Gravelly Beach",
    "Grindelwald",
    "Grove",
    "Hadspen",
    "Hagley",
    "Hamilton",
    "Hawley",
    "Henrietta",
    "Herdsmans Cove",
    "Hillcrest",
    "Hobart",
    "Howden",
    "Howrah",
    "Huonville",
    "Invermay",
    "Kettering",
    "Kings Meadows",
    "Kingston",
    "Lachlan",
    "Latrobe",
    "Lauderdale",
    "Launceston",
    "Legana",
    "Lenah Valley",
    "Levendale",
    "Lewisham",
    "Lilydale",
    "Lindisfarne",
    "Loira",
    "Longford",
    "Low Head",
    "Lower Barrington",
    "Lower Longley",
    "Lower Sandy Bay",
    "Lucaston",
    "Lutana",
    "Magra",
    "Margate",
    "Mawbanna",
    "Maydena",
    "Mayfield",
    "Meander",
    "Mengha",
    "Miandetta",
    "Midway Point",
    "Molesworth",
    "Montello",
    "Montrose",
    "Moonah",
    "Mornington",
    "Mount Hicks",
    "Mount Nelson",
    "Mount Rumney",
    "Mount Stuart",
    "Mountain River",
    "Mowbray",
    "Murdunna",
    "Natone",
    "New Norfolk",
    "New Town",
    "Newnham",
    "Newstead",
    "Nicholls Rivulet",
    "Nile",
    "North Hobart",
    "North Scottsdale",
    "Norwood",
    "Nugent",
    "Nunamara",
    "Oakdowns",
    "Oatlands",
    "Old Beach",
    "Orford",
    "Ouse",
    "Oyster Cove",
    "Park Grove",
    "Parrawe",
    "Penguin",
    "Penna",
    "Perth",
    "Pipers River",
    "Plenty",
    "Pontville",
    "Port Huon",
    "Port Sorell",
    "Preolenna",
    "Primrose Sands",
    "Prospect",
    "Punchbowl",
    "Queens Domain",
    "Quoiba",
    "Railton",
    "Ranelagh",
    "Ravenswood",
    "Red Hills",
    "Relbia",
    "Richmond",
    "Ridgley",
    "Risdon",
    "Risdon Vale",
    "Riverside",
    "Rocherlea",
    "Roches Beach",
    "Rocky Cape",
    "Rokeby",
    "Romaine",
    "Rose Bay",
    "Rosebery",
    "Rosetta",
    "Rosevears",
    "Rowella",
    "Sandfly",
    "Sandford",
    "Sandy Bay",
    "Sassafras",
    "Scottsdale",
    "Seven Mile Beach",
    "Shearwater",
    "Sheffield",
    "Shorewell Park",
    "Smithton",
    "Snug",
    "Somerset",
    "Sorell",
    "South Arm",
    "South Burnie",
    "South Hobart",
    "South Launceston",
    "South Riana",
    "South Spreyton",
    "Sprent",
    "Spreyton",
    "Squeaking Point",
    "St Helens",
    "St Leonards",
    "Staverton",
    "Stony Rise",
    "Summerhill",
    "Swan Bay",
    "Swansea",
    "Takone",
    "Tarleton",
    "The Glebe",
    "Togari",
    "Trevallyn",
    "Triabunna",
    "Trial Bay",
    "Tugrah",
    "Turners Beach",
    "Ulverstone",
    "Upper Burnie",
    "Upper Natone",
    "Upper Scamander",
    "Upper Stowport",
    "Upper Woodstock",
    "Waratah",
    "Warrane",
    "Waverley",
    "Weegena",
    "Wesley Vale",
    "West Hobart",
    "West Launceston",
    "West Moonah",
    "West Mooreville",
    "West Ulverstone",
    "Westbury",
    "Westwood",
    "White Beach",
    "Wilburville",
    "Wilmot",
    "Wynyard",
    "Yolla",
    "Zeehan",
]
