"""standalone sightings and pet links

Revision ID: 0c6b02e2528c
Revises: 455eec904886
Create Date: 2026-08-16 19:20:24.836261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6b02e2528c'
down_revision = '455eec904886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('sighting_id', sa.Integer(), nullable=True),
    sa.Column('linked_pet_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(sighting_id IS NOT NULL AND linked_pet_id IS NULL) OR (sighting_id IS NULL AND linked_pet_id IS NOT NULL)', name='ck_pet_links_one_target'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'linked_pet_id', name='uq_pet_links_pet'),
    sa.UniqueConstraint('pet_id', 'sighting_id', name='uq_pet_links_sighting')
    )
    with op.batch_alter_table('pet_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_links_linked_pet_id'), ['linked_pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_links_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_links_sighting_id'), ['sighting_id'], unique=False)

    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('species')

    with op.batch_alter_table('pet_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_links_sighting_id'))
        batch_op.drop_index(batch_op.f('ix_pet_links_pet_id'))
        batch_op.drop_index(batch_op.f('ix_pet_links_linked_pet_id'))

    op.drop_table('pet_links')
    # ### end Alembic commands ###
