"""email verification on users

Revision ID: 3b22f4f6cdf7
Revises: 4c401166a664
Create Date: 2026-08-16 17:24:28.202171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b22f4f6cdf7'
down_revision = '4c401166a664'
branch_labels = None
depends_on = None


def upgrade():
    # server_default=sa.false(), never sa.text('0') — autogenerate renders the
    # SQLite form and Postgres rejects it. See the note in the baseline
    # migration; tests/test_migrations.py catches a regression.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(),
                                      server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True),
                                      nullable=True))
        batch_op.add_column(sa.Column('verification_sent_at', sa.DateTime(timezone=True),
                                      nullable=True))

    # Accounts that predate verification are treated as confirmed. They signed
    # up when nothing asked them to confirm, so retroactively cutting them off
    # from messaging and sightings would punish them for a feature arriving —
    # and on an instance with no mail provider they would have no way back.
    op.execute(sa.text(
        "UPDATE users SET email_verified = true, email_verified_at = created_at"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_sent_at')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
