"""per-user geocode budget

Revision ID: 455eec904886
Revises: 3b22f4f6cdf7
Create Date: 2026-08-16 18:47:15.659311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455eec904886'
down_revision = '3b22f4f6cdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocode_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('geocode_window_start', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('geocode_window_start')
        batch_op.drop_column('geocode_count')

    # ### end Alembic commands ###
