"""search tracks: GPS and drone coverage

Revision ID: 4c401166a664
Revises: 85d622b0d011
Create Date: 2026-08-16 14:31:55.734213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c401166a664'
down_revision = '85d622b0d011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='on_foot', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points', sa.LargeBinary(), nullable=True),
    sa.Column('cells', sa.LargeBinary(), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('cell_count', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('min_lng', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.Column('max_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_removed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('removed_by_id', sa.Integer(), nullable=True),
    sa.Column('removed_reason', sa.String(length=500), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_tracks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_tracks_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_tracks_is_removed'), ['is_removed'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_tracks_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_tracks_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_tracks_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_tracks_bbox', ['min_lat', 'min_lng', 'max_lat', 'max_lng'], unique=False)
        batch_op.create_index('ix_tracks_visible', ['is_removed', 'finished_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_tracks_visible')
        batch_op.drop_index('ix_tracks_bbox')
        batch_op.drop_index(batch_op.f('ix_search_tracks_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_tracks_started_at'))
        batch_op.drop_index(batch_op.f('ix_search_tracks_pet_id'))
        batch_op.drop_index(batch_op.f('ix_search_tracks_is_removed'))
        batch_op.drop_index(batch_op.f('ix_search_tracks_finished_at'))
        batch_op.drop_index(batch_op.f('ix_search_tracks_created_at'))

    op.drop_table('search_tracks')
    # ### end Alembic commands ###
