"""baseline: users, pets, photos, sightings, contact messages, geocode cache

Revision ID: 85d622b0d011
Revises:
Create Date: 2026-08-16 11:38:40.028203

NOTE FOR FUTURE AUTOGENERATED MIGRATIONS
----------------------------------------
Boolean server defaults must be written ``sa.false()`` / ``sa.true()``, never
``sa.text('0')`` / ``sa.text('1')``.

``flask db migrate`` run against the local SQLite database renders the models'
``db.false()`` into the literal ``sa.text('0')``, because that is what the
SQLite dialect emits. Postgres then rejects the resulting DDL outright —
"column is of type boolean but default expression is of type integer" — so a
migration generated on SQLite fails on deploy while passing every local test.
``sa.false()`` is dialect-aware and renders correctly for both.

Check every new boolean column for this before pushing.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d622b0d011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('formatted', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geocode_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geocode_cache_normalized_address'), ['normalized_address'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('species', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('colour', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('size', sa.String(length=16), nullable=True),
    sa.Column('microchipped', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('collar', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('public_lat', sa.Float(), nullable=False),
    sa.Column('public_lng', sa.Float(), nullable=False),
    sa.Column('blur_location', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('address_raw', sa.String(length=300), nullable=True),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('show_phone', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_removed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('removed_by_id', sa.Integer(), nullable=True),
    sa.Column('removed_reason', sa.String(length=500), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_index('ix_pets_bbox', ['public_lat', 'public_lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_is_removed'), ['is_removed'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_locality'), ['locality'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pets_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_pets_visible', ['is_removed', 'status', 'report_type'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('pet_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('thumb', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_photos_pet_id'), ['pet_id'], unique=False)

    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('photo_mimetype', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_removed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('removed_by_id', sa.Integer(), nullable=True),
    sa.Column('removed_reason', sa.String(length=500), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sightings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sightings_is_removed'), ['is_removed'], unique=False)
        batch_op.create_index(batch_op.f('ix_sightings_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sightings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sightings_user_id'))
        batch_op.drop_index(batch_op.f('ix_sightings_pet_id'))
        batch_op.drop_index(batch_op.f('ix_sightings_is_removed'))
        batch_op.drop_index(batch_op.f('ix_sightings_created_at'))

    op.drop_table('sightings')
    with op.batch_alter_table('pet_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_photos_pet_id'))

    op.drop_table('pet_photos')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_pet_id'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_index('ix_pets_visible')
        batch_op.drop_index(batch_op.f('ix_pets_user_id'))
        batch_op.drop_index(batch_op.f('ix_pets_status'))
        batch_op.drop_index(batch_op.f('ix_pets_report_type'))
        batch_op.drop_index(batch_op.f('ix_pets_locality'))
        batch_op.drop_index(batch_op.f('ix_pets_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_pets_is_removed'))
        batch_op.drop_index(batch_op.f('ix_pets_created_at'))
        batch_op.drop_index('ix_pets_bbox')

    op.drop_table('pets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('geocode_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geocode_cache_normalized_address'))

    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
