"""per-pet match alert budget

Revision ID: cac400e5f87a
Revises: 0c6b02e2528c
Create Date: 2026-08-16 19:59:03.446158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac400e5f87a'
down_revision = '0c6b02e2528c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_alerts_sent', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('match_alert_window_start', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('match_alert_window_start')
        batch_op.drop_column('match_alerts_sent')

    # ### end Alembic commands ###
